### ISSUE TITLE
API no longer returning total_score, votes_agreed, and votes_total in session object

### ISSUE THREAD

**Issue by rfriberg** [aclu-national/elections-api#10]
The Scorecards site is relying on three `session` attributes (`total_score`, `votes_agreed`, `votes_total`) that appear to be missing from the elections API.  

This is (more or less) the expected object for a single session:
```js
    // Example session object:
    sessions: [{
      display_name: 'Rep. Nanette Barragan',
      running_in_2018: false,
      running_for_president: false,
      scores: [{
        aclu_id: 'aclu/us-congress-116/sen_score:1',
        aclu_position: 'opposed',
        name: 'Name of bill',
        status: 'voted',
        vote: false,
        vote_matches_aclu_position: false
      }],
      session: 116,
      total_score: '',
      votes_agreed: '',
      votes_total: ''
    }],
```

This is a screenshot of the `session` object I'm currently seeing:
<img width="404" alt="Screenshot 2019-05-21 15 40 06" src="https://user-images.githubusercontent.com/1463386/58135305-c59f0500-7bde-11e9-9edf-9ea1a8cb9f4a.png">

Currently seen on both prod and staging and multiple endpoints:
https://elections.api.aclu.org/v2/congress/legislators?url_slug=ca-kamala-harris&session=116
https://elections-stg.api.aclu.org/v2/congress/legislators?url_slug=ca-kamala-harris&session=116
https://elections.api.aclu.org/v2/geoip?legislators=1&session=116

Effects can be seen on https://www.aclu.org/scorecard/ where no scores are showing up.

**Comment by rfriberg** [comment]
Thanks for fixing @kateray!  Closing

**Comment by kateray** [comment]
Fixed by running "make congress_details && make congress_scores" on the servers (both prod and staging)
